# Generated by Django 5.1.3 on 2024-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_designrequest_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято в работу'), ('completed', 'Выполнено')], default='new', max_length=20),
        ),
    ]
